#!/usr/bin/python3

import pigpio
import time

pi = pigpio.pi

try:
    while True:
        pi.set_servo_pulsewidth(26, 700)
        time.sleep(0.25)
        pi.set_servo_pulsewidth(6, 1500)
        time.sleep(0.25)
except KeyboardInterrupt:
    pi.stop()